src/assets/css/PlanCard.css
src/pages/Landing/LandingPage.jsx

[황민영] 🎨style: css 수정

---

package-lock.json
package.json
src/assets/css/global.css
src/components/common/Footer.jsx

Reverts wainou06/YORE_frontend#3

Revert ":예술: style : footer css 수정"

---

src/components/common/Footer.jsx
src/pages/Error/NotFoundPage.jsx
src/routes/index.jsx

[황민영] ✨: feat: 404 페이지 추가

---

src/pages/Legal/PrivacyPage.jsx
src/pages/Legal/TermsPage.jsx
src/routes/index.jsx

[황민영] ✨: 페이지 추가

---

src/components/common/LoginWidget.jsx

[전준모] ✨ feat: 로그인 기능 추가

---

src/components/common/KakaoCallback.jsx
src/components/common/LoginWidget.jsx
src/pages/Auth/SignupPage.jsx
src/routes/index.jsx

[전준모] ✨feat: 카카오 연동 기능 추가

---

src/features/auth/authSlice.js
src/routes/AdminRoute.jsx
src/services/api.js
src/services/planService.js

[황민영] ✨ feat : 모델 수정에 따른 슬라이스 및 라우터 수정

[황민영] ✨ feat : 모델 수정에 따른 슬라이스 및 라우터 수정

---

src/assets/css/LoginWidget.css
src/components/common/LoginWidget.jsx
src/pages/Auth/SignupPage.jsx

[전준모] 🎨 style: 컴포넌트 분류

---

src/assets/css/PlanSettings.css
src/pages/Auth/Billing.jsx
src/pages/Auth/PlanSettings.jsx

[전준모] ✨feat : 나의 정보 관련 페이지 추가

---

src/api/axiosApi.js
src/api/plansApi.js
src/api/servicesApi.js
src/app/store.js
src/components/common/Header.jsx
src/components/plans/BasicInfoForm.jsx
src/features/plans/planSlice.js
src/features/services/serviceSlice.js
src/pages/Agency/AgencyPlanList.jsx
src/pages/Auth/Billing.jsx
src/pages/Auth/PlanSettings.jsx
src/pages/Plans/PlanCreatePage.jsx
src/routes/AgencyRoute.jsx

[황민영] ✅ test : 테스트 완료, 데이터 값 필요

[황민영] ✅ test : 테스트 완료, 데이터 값 필요

---

src/api/plansApi.js
src/components/plans/PlanCard.jsx
src/components/plans/PlanFilters.jsx
src/components/shared/PlanFilters.jsx
src/features/plans/planSlice.js
src/pages/Agency/AgencyPlanList.jsx
src/pages/Plans/PlanListPage.jsx

[황민영] ✨ feat : 요금제 조회 가능!

---

src/api/transactionsApi.js
src/api/userPlansApi.js
src/app/store.js
src/components/plans/PlanQuotaForm.jsx
src/components/plans/PriceSummary.jsx
src/features/transactions/transactionSlice.js
src/features/userPlans/userPlanSlice.js
src/pages/Plans/PlanCreatePage.jsx
src/pages/Plans/PlanDetailPage.jsx

[황민영] ✨ feat : 결제 및 플랜 생성만 구현

---

src/components/common/NotificationDropdown.jsx
src/pages/Plans/PlanCreatePage.jsx

[황민영] 📝 docs : 알람 바로 읽음 처리, 요금제 생성 때는 할인 한 금액 들어가면 안 됨

[황민영] 📝 docs : 알람 바로 읽음 처리, 요금제 생성 때는 할인 한 금액 들어가면 안 됨

---

src/api/userPlansApi.js
src/assets/css/global.css
src/features/userPlans/userPlanSlice.js
src/pages/Auth/Billing.jsx
src/pages/Auth/PlanSettings.jsx

[황민영] ✨ feat : 요금제 관련 구현

---

src/pages/Plans/PlanCreatePage.jsx

[황민영] 🐛 fix : 등록 버그 수정

---

src/components/plans/PriceSummary.jsx

[황민영] 🐛 fix : 옵션 변경 시 userId, planId 값 바로 받기

[황민영] 🐛 fix : 옵션 변경 시 userId, planId 값 바로 받기

---

src/assets/css/LoginWidget.css
src/components/common/LoginWidget.jsx

[전준모] ✨ feat : 엔터 누를시 로그인

---

src/api/surveyApi.js
src/app/store.js
src/components/plans/RecommendPlans.jsx
src/features/survey/surveySlice.js
src/pages/Landing/LandingPage.jsx

[황민영] ✨ feat : 추천 요금제 생성, 조회

---

src/components/common/Footer.jsx
src/components/common/Header.jsx
src/pages/Auth/MyInfo.jsx

[전준모] 🎨style: CSS 수정

---

src/components/plans/PriceSummary.jsx

[황민영] ✨ feat : 정말 결제할 건가요? 모달

---

src/components/common/LoginWidget.jsx
src/pages/Auth/MyInfo.jsx

[전준모] 🐛 fix: 로그인 오류 해결

---

src/components/common/LoginWidget.jsx

[황민영] 📝 docs : 기업회원 없어짐, 다시 추가

[황민영] 📝 docs : 기업회원 없어짐, 다시 추가

---

src/api/axiosApi.js
src/components/common/LoginWidget.jsx
src/components/plans/PlanCard.jsx
src/components/plans/PlanFilters.jsx
src/features/auth/authSlice.js
src/pages/Admin/PlanManagement.jsx
src/pages/Agency/AgencySettings.jsx
src/pages/Auth/MySettings.jsx
src/pages/Carriers/CarrierListPage.jsx

[황민영] 📝 docs : UI/UX 점검, 오류 메세지 추가, 수정

[황민영] 📝 docs : UI/UX 점검, 오류 메세지 추가, 수정

---

src/api/authApi.js
src/assets/css/MySettings.css
src/components/common/KakaoCallback.jsx
src/components/common/LoginWidget.jsx
src/components/common/Modal.jsx
src/components/common/modals/ModalPw.jsx
src/features/agency/agencySlice.js
src/features/auth/authSlice.js
src/pages/Agency/AgencyPlanList.jsx
src/pages/Auth/Billing.jsx
src/pages/Auth/MyInfo.jsx
src/pages/Auth/MySettings.jsx
src/pages/Auth/SignupPage.jsx

[전준모] 🎨 style: CSS 작업, 불필요한 정보 제거

[전준모] 🎨 style: CSS 작업, 불필요한 정보 제거

---

src/assets/css/PlanCard.css
src/pages/Carriers/CarrierListPage.jsx
src/pages/Landing/LandingPage.jsx

[황민영] 🎨 style : css 수정, 이미지 추가

[황민영] 🎨 style : css 수정, 이미지 추가

---

src/api/authApi.js
src/features/auth/authSlice.js
src/pages/Auth/MySettings.jsx

[전준모] ✨ feat : 회원 탈퇴 기능 추가

---

src/features/userPlans/userPlanSlice.js
src/pages/Auth/MyInfo.jsx

[전준모] 🐛 fix : 나의 정보 오류 수정

---

src/components/common/LoginWidget.jsx
src/pages/Auth/MyInfo.jsx
src/pages/Auth/MySettings.jsx
src/pages/Carriers/CarrierListPage.jsx

[전준모] 🐛 fix : env 파일 수정
